# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/EmbeddedVision/constraints/top.xdc

# Block Designs: C:/Projects/EmbeddedVision/BD/bd_embVision/bd_embVision.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision || ORIG_REF_NAME==bd_embVision} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_processing_system7_0_0/bd_embVision_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_processing_system7_0_0 || ORIG_REF_NAME==bd_embVision_processing_system7_0_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_img_buffer_0_0/bd_embVision_img_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_img_buffer_0_0 || ORIG_REF_NAME==bd_embVision_img_buffer_0_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_ps7_0_axi_periph_0/bd_embVision_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_embVision_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_rst_ps7_0_100M_0/bd_embVision_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_rst_ps7_0_100M_0 || ORIG_REF_NAME==bd_embVision_rst_ps7_0_100M_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_vga_timing_controller_0_0/bd_embVision_vga_timing_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_vga_timing_controller_0_0 || ORIG_REF_NAME==bd_embVision_vga_timing_controller_0_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_xbar_0/bd_embVision_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_xbar_0 || ORIG_REF_NAME==bd_embVision_xbar_0} -quiet] -quiet

# IP: c:/Projects/EmbeddedVision/BD/bd_embVision/ip/bd_embVision_auto_pc_0/bd_embVision_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_embVision_auto_pc_0 || ORIG_REF_NAME==bd_embVision_auto_pc_0} -quiet] -quiet

# XDC: C:/Projects/EmbeddedVision/BD/bd_embVision/bd_embVision_ooc.xdc
